### ISSUE TITLE
Is there a way to dispatch actions from main?

### ISSUE THREAD

**Issue by juliuszc** [samiskin/redux-electron-store#15]
Currently, when I try to dispatch an action from main, I get an uncaught exception: "Cannot assign to read only property 'source' of ACTION at store.dispatch.  Sorry, if I'm trying to do something dumb.

**Comment by samiskin** [comment]
Hm strange, dispatching should work regardless of whether its from the main process or outside.  Right now I assign `action.source`, so maybe that's conflicting with another library?  Could you try removing `redux-electron-store`, then see if theres anything currently set with `action.source`, or maybe something making `action` read-only?

**Comment by juliuszc** [comment]
Sorry, turns out I was just doing something dumb!

**Comment by samiskin** [comment]
No problem, its a reasonable case that the action object might be frozen in some way, so I should deal with it :+1:  Thanks for pointing it out!
