### ISSUE TITLE
Consider using individual lodash modules

### ISSUE THREAD

**Issue by davej** [samiskin/redux-electron-store#20]
I wonder would you consider requiring the individual lodash modules instead of doing a catch-all import.

```js
// Instead of this:
import _ from 'lodash';

// You could do this:
import cloneDeep from 'lodash/cloneDeep';
```

I'm on a mission to trim down my electron app and improve boot time, lodash is one of the prime offenders, see screenshot below.

![image](https://cloud.githubusercontent.com/assets/26971/15612606/6bd3f8a8-2427-11e6-9413-80da2706c00b.png)

**Comment by samiskin** [comment]
Sure, I'll get it done within the next couple days :+1:

**Comment by paulcbetts** [comment]
@samiskin Don't do it yourself, make @davej submit a PR :)

**Comment by paulcbetts** [comment]
Never fix bugs in open-source projects when you can be teaching the reporter how to submit a PR instead

**Comment by samiskin** [comment]
Ah makes sense.  Well then, @davej could you submit a PR for it? 😛

**Comment by davej** [comment]
Haha, sure, I'm on it now :)

**Comment by davej** [comment]
Ok, should be good to go. Did some brief manual testing on my app and all seems to be well. The package is also super-light now. :)
