### ISSUE TITLE
actions dispatched in .subscribe aren't syncing

### ISSUE THREAD

**Issue by bgrayburn** [samiskin/redux-electron-store#26]
I can't figure out why, but I have a few actions that are called in a store.subscribe on the main process, but these aren't synched with the renderer. Any idea why? Thanks for this great library, definitely made things simpler.

**Comment by bgrayburn** [comment]
in devtron, I'm seeing the __REDUX_ELECTRON_-browser-dispatch, but the store on the renderer never runs for that action, now I'm really confused, it's only for actions called in .subscribe. I even put a _.clone in my reducer to make sure I was updating properly.

**Comment by samiskin** [comment]
Fixed in `v0.3.12` :+1:  Thanks for the report!

I also fixed the issue where the actions would appear out of order, so if you dispatched action 1, then action 2 in `subscribe`, the other renderers would receive action 2, then receive action 1.
