### ISSUE TITLE
Custom subscribe breaks itch.io/app

### ISSUE THREAD

**Issue by fasterthanlime** [samiskin/redux-electron-store#27]
I haven't git bisect'd but I have a stack trace that seems related to 95decf069582979bdf812b257e80464f60ec42ca

![virtualbox_archlinux_02_08_2016_19_40_00](https://cloud.githubusercontent.com/assets/7998310/17338767/086707aa-58e9-11e6-8ef5-9b2aa8f01825.png)

I'm still investigating why this happens, will have to pin to an older version in the meantime

**Comment by fasterthanlime** [comment]
Actual stack trace:

<details>
<summary>/home/osboxes/Dev/itch/node_modules/redux-electron-store/lib/getSubscribeFuncs.js:34 Uncaught Error: You may not unsubscribe from a store listener while the reducer is executing</summary>
unsubscribe @ /home/osboxes/Dev/itch/node_modules/redux-electron-store/lib/getSubscribeFuncs.js:34
tryUnsubscribe @ /home/osboxes/Dev/itch/node_modules/react-redux/lib/components/connect.js:245
componentWillUnmount @ /home/osboxes/Dev/itch/node_modules/react-redux/lib/components/connect.js:261
unmountComponent @ /home/osboxes/Dev/itch/node_modules/react/lib/ReactCompositeComponent.js:435
unmountComponent @ /home/osboxes/Dev/itch/node_modules/react/lib/ReactReconciler.js:81
updateChildren @ /home/osboxes/Dev/itch/node_modules/react/lib/ReactChildReconciler.js:112
_reconcilerUpdateChildren @ /home/osboxes/Dev/itch/node_modules/react/lib/ReactMultiChild.js:213
_updateChildren @ /home/osboxes/Dev/itch/node_modules/react/lib/ReactMultiChild.js:316
updateChildren @ /home/osboxes/Dev/itch/node_modules/react/lib/ReactMultiChild.js:303
_updateDOMChildren @ /home/osboxes/Dev/itch/node_modules/react/lib/ReactDOMComponent.js:960
updateComponent @ /home/osboxes/Dev/itch/node_modules/react/lib/ReactDOMComponent.js:780
receiveComponent @ /home/osboxes/Dev/itch/node_modules/react/lib/ReactDOMComponent.js:734
receiveComponent @ /home/osboxes/Dev/itch/node_modules/react/lib/ReactReconciler.js:129
updateChildren @ /home/osboxes/Dev/itch/node_modules/react/lib/ReactChildReconciler.js:107
_reconcilerUpdateChildren @ /home/osboxes/Dev/itch/node_modules/react/lib/ReactMultiChild.js:213
_updateChildren @ /home/osboxes/Dev/itch/node_modules/react/lib/ReactMultiChild.js:316
updateChildren @ /home/osboxes/Dev/itch/node_modules/react/lib/ReactMultiChild.js:303
_updateDOMChildren @ /home/osboxes/Dev/itch/node_modules/react/lib/ReactDOMComponent.js:960
updateComponent @ /home/osboxes/Dev/itch/node_modules/react/lib/ReactDOMComponent.js:780
receiveComponent @ /home/osboxes/Dev/itch/node_modules/react/lib/ReactDOMComponent.js:734
receiveComponent @ /home/osboxes/Dev/itch/node_modules/react/lib/ReactReconciler.js:129
_updateRenderedComponent @ /home/osboxes/Dev/itch/node_modules/react/lib/ReactCompositeComponent.js:784
_performComponentUpdate @ /home/osboxes/Dev/itch/node_modules/react/lib/ReactCompositeComponent.js:753
updateComponent @ /home/osboxes/Dev/itch/node_modules/react/lib/ReactCompositeComponent.js:670
receiveComponent @ /home/osboxes/Dev/itch/node_modules/react/lib/ReactCompositeComponent.js:564
receiveComponent @ /home/osboxes/Dev/itch/node_modules/react/lib/ReactReconciler.js:129
_updateRenderedComponent @ /home/osboxes/Dev/itch/node_modules/react/lib/ReactCompositeComponent.js:784
_performComponentUpdate @ /home/osboxes/Dev/itch/node_modules/react/lib/ReactCompositeComponent.js:753
updateComponent @ /home/osboxes/Dev/itch/node_modules/react/lib/ReactCompositeComponent.js:670
performUpdateIfNecessary @ /home/osboxes/Dev/itch/node_modules/react/lib/ReactCompositeComponent.js:578
performUpdateIfNecessary @ /home/osboxes/Dev/itch/node_modules/react/lib/ReactReconciler.js:163
runBatchedUpdates @ /home/osboxes/Dev/itch/node_modules/react/lib/ReactUpdates.js:151
perform @ /home/osboxes/Dev/itch/node_modules/react/lib/Transaction.js:138
perform @ /home/osboxes/Dev/itch/node_modules/react/lib/Transaction.js:138
perform @ /home/osboxes/Dev/itch/node_modules/react/lib/ReactUpdates.js:90
flushBatchedUpdates @ /home/osboxes/Dev/itch/node_modules/react/lib/ReactUpdates.js:173
closeAll @ /home/osboxes/Dev/itch/node_modules/react/lib/Transaction.js:204
perform @ /home/osboxes/Dev/itch/node_modules/react/lib/Transaction.js:151
batchedUpdates @ /home/osboxes/Dev/itch/node_modules/react/lib/ReactDefaultBatchingStrategy.js:63
enqueueUpdate @ /home/osboxes/Dev/itch/node_modules/react/lib/ReactUpdates.js:201
enqueueUpdate @ /home/osboxes/Dev/itch/node_modules/react/lib/ReactUpdateQueue.js:25
enqueueSetState @ /home/osboxes/Dev/itch/node_modules/react/lib/ReactUpdateQueue.js:210
ReactComponent.setState @ /home/osboxes/Dev/itch/node_modules/react/lib/ReactComponent.js:64
handleChange @ /home/osboxes/Dev/itch/node_modules/react-redux/lib/components/connect.js:301
(anonymous function) @ /home/osboxes/Dev/itch/node_modules/redux-electron-store/lib/getSubscribeFuncs.js:45
callListeners @ /home/osboxes/Dev/itch/node_modules/redux-electron-store/lib/getSubscribeFuncs.js:44
(anonymous function) @ /home/osboxes/Dev/itch/node_modules/redux-electron-store/lib/electronRendererEnhancer.js:150
emitTwo @ events.js:106
emit @ events.js:191
</details>

**Comment by fasterthanlime** [comment]
You can reproduce by cloning https://github.com/itchio/itch, checking out the `v18.4.5-canary` tag, and following the README instructions to start it (TL;DR - `npm install && npm install -g electron-prebuilt@1.2.8 && npm start`)

**Comment by paulcbetts** [comment]
Yup, we were broken by this too

**Comment by JodusNodus** [comment]
Same here

**Comment by samiskin** [comment]
@fasterthanlime @paulcbetts @JodusNodus Could you all confirm if this still happens in `v0.3.13`?

**Comment by fasterthanlime** [comment]
@samiskin 0.3.13 seems fine to me!

**Comment by fasterthanlime** [comment]
Fixed in 0.3.13

**Comment by JodusNodus** [comment]
👍 Working perfectly.
