### ISSUE TITLE
Add example with hot reloading

### ISSUE THREAD

**Issue by jhen0409** [samiskin/redux-electron-store#3]
First thanks this great work! :D
I simply tried this module with the webpack hot reload, see following code, it used counter example:

#### Main process (with babel-core/register)

```js
import thunk from 'redux-thunk';
import rootReducer from '../reducers';
import { electronEnhancer } from 'redux-electron-store';
import { createStore, applyMiddleware, compose } from 'redux';
import { ipcMain } from 'electron';

const finalCreateStore = compose(
  applyMiddleware(thunk),
  electronEnhancer({})
)(createStore);

export default function configureStore(initialState) {
  const store = finalCreateStore(rootReducer, initialState);

  ipcMain.on('renderer-reload', (event, action) => {
    delete require.cache[require.resolve('../reducers')];
    delete require.cache[require.resolve('../reducers/counter')];
    store.replaceReducer(require('../reducers'));
    event.returnValue = true;
  });

  return store;
}
```

#### Renderer process (with webpack)

```js
import thunk from 'redux-thunk';
import rootReducer from '../reducers';
import DevTools from '../containers/DevTools';
import { createStore, applyMiddleware, compose } from 'redux';
import { ipcRenderer } from 'electron';
import { electronEnhancer } from 'redux-electron-store';

const finalCreateStore = compose(
  applyMiddleware(thunk),
  electronEnhancer({}),
  DevTools.instrument()
)(createStore);

export default function configureStore(initialState) {
  const store = finalCreateStore(rootReducer, initialState);

  if (module.hot) {
    module.hot.accept('../reducers', () => {
      ipcRenderer.sendSync('renderer-reload');
      store.replaceReducer(require('../reducers'))
    });
  }

  return store;
}
```
There a better way to delete cache of main process?

**Comment by samiskin** [comment]
I am currently working on an example and I will make sure to try this out!

**Comment by samiskin** [comment]
I *finally* got to trying this out, terribly sorry for taking an entire 4 months to do so.  Unfortunately I didn't meet much success while using webpack for my main process files.

I had hoped that http://stackoverflow.com/a/14801711 would work out, however I had no luck.  It might work when webpack isn't used for the main process (it handles dynamic requires in a special way).

For me it seemed that deleting only `'../reducers'` would also invalidate `../reducers/counter` as long as I didn't require `counter` separately, so I guess your way would still work as long as reducers are only included by other reducers.

**Comment by samiskin** [comment]
Forgot to mention:
  I put example code in the README, thanks for suggesting it!
