### ISSUE TITLE
Blocking non viable json objects from main process before sending it to renderer process

### ISSUE THREAD

**Issue by ernstluring** [samiskin/redux-electron-store#30]
Hi, first of all thanks for creating this library.

At the moment I've a small issue with starting up a game engine building process with a Node process and a socket. This building happens in the main process where it stores this Node process and the socket in its store and it needs to push some data to a renderer process. But the Node process and the socket aren't json viable so these things can't be send to the renderer process, that's fine because the renderer process doesn't need to know about this. So I tried to use the filter option in the renderer process to only let through the json viable data, but the problem is that the main process still sends it to the renderer process and because of this I'm getting "converting circular structure to JSON" errors. 

Do you see a solution for this? I thought about adjusting the BrowserEnhancer so it checks the data before it sends it through ipc, but maybe you have a better solution?

Thanks!

**Comment by samiskin** [comment]
Hmm, the point of the filter is partly to solve this type of issue.  Is it erroring right at the beginning?  My guess is that its happening because of the `let browserStore = remote.getGlobal(globalName);` at the beginning but I'd like to confirm that.

**Comment by ernstluring** [comment]
Thanks for your respond!
It is not happening on every dispatch, only on a dispatch with a action that contains a node process or a socket. This is the error message I get (so I think it errors in the beginning):

> Uncaught Exception:
TypeError: Converting circular structure to JSON at store.dispatch
(...\node_modules\redux-electron-store\lib\electronBr....:45)

To be sure, my filter on the renderer process looks like this:
`application: {
            loadingText:true,
            loadingBlocking:true,
            errorText:true,
            tab:true,
            gameState:true,
            builderState:true,
            builderErrors:true,
            toolTab:true
}`
So the variables in the application I don't want to pass aren't included, is that the right way?

**Comment by ernstluring** [comment]
I solved the problem! Maybe it was a bit of a silly mistake. I had an action with 3 arguments: a string for setting the builder state name, a possible process and a possible socket (I'm using typescript btw). I separated this action to 3 different actions, one for each of these arguments and know it is working. I didn't thought about this, but the action is of course in its whole pushed to the renderer process.

Thanks for your help non the less!

**Comment by samiskin** [comment]
Ah so the action object itself contained a circular structure?  That seems like a very reasonable mistake to make.  I'll try to solve that / put a more helpful error for that case next time I get the chance to work on this :+1:

Thanks for submitting the issue!  Always helpful to know how this is being used in the wild.
