### ISSUE TITLE
application hangs on redux-electron-store

### ISSUE THREAD

**Issue by hyalkaf** [samiskin/redux-electron-store#39]
Thank you for this library as it helps syncing electron windows to the store. I have successfully used this library but lately I was fixing linting errors in my app and when I tried to run the app again, it will hang on a line on `electronRendererEnhancer.js`

The line is: `subscribeFuncs.callListeners();`

It gets stuck there after dispatching a specific action. Some actions are working but once I dispatch that specific action, it will go through reducers normally and then go to electronRendererEnhancer and gets stuck there. I'm not sure why is this happening all of a sudden after it used to work. I used to have an older version and updated it to a new version but I tried to go back to the older version and still no luck. Changes that I made from when it was working to now are:

- Changed react files extension to jsx

- Fixed a lot of linting errors (this is probably where I changed something that affected it?)

- Updated some libraries.

**Comment by samiskin** [comment]
I'm afraid I'd need more information in order to look into this.  Could you try to figure out precisely what changed started the issue?  And to be clear, there's no JavaScript error, it just seems to freeze indefinitely when executing `subscribeFuncs.callListeners()`?

**Comment by hyalkaf** [comment]
Just figured it out, nothing to do with electron-redux-store. There was a loop in my code that was running indefinitely after being called in componentWillReceiveProps. Sorry about this.

**Comment by samiskin** [comment]
No worries, I'm glad you figured it out 👍
