### ISSUE TITLE
Is there an easy way to clear store for testing like normally ctrl + R?

### ISSUE THREAD

**Issue by Superjo149** [samiskin/redux-electron-store#41]
When working with a redux store only in the renderer process, we were able to refresh this with the page by using ctrl + r for example. Since this is synced now, is there an easy way to clear everything when the renderer clears?

**Comment by samiskin** [comment]
If your goal is simply to set the store back to its original state, you could just dispatch an action that does so (with the appropriate reducer set up that just returns the initial state).  

For easy debugging what I sometimes do is just expose my store as a global object in the renderer, like `window.REDUX_STORE`, and then I could just open up the console and type `REDUX_STORE.dispatch({type: 'RESET'})`.  whenever I would want to clear it.

**Comment by samiskin** [comment]
Closing since it sounds like you're all set :+1:
