### ISSUE TITLE
electronEnhancer does not load Initial State correctly

### ISSUE THREAD

**Issue by initFabian** [samiskin/redux-electron-store#50]
Hello,

I encountered an issue when loading the initial state of an application. Let me paint a quick picture. 

I have a sidebar in my application and when the application loads(regardless of the previous state), the sidebar will be hidden. I am doing that by setting some initial state when the application loads.

```javascript

export const StoreFactory = (initialState): Store<StoreState> => {
    
    if (!store) {
        let middleware = (() => {
            return applyMiddleware(thunk)
        })()

        let enhancer = compose(
            middleware,
            electronEnhancer({
                dispatchProxy: a => store.dispatch(a),
            })
        )
        // here !!
        let initialStateWithHiddenAppearence = Object.assign({}, initialState, {
            appearence: {
                leftSidebarVisibility: false
            }
        })
        store = createStore(appReducer, initialStateWithHiddenAppearence, enhancer)
    }

    return store
}
```

But when inspecting `store.getState()` at the end of `StoreFactory`, the application's previous state is loaded. 

After further inspection, I traced the bug down to `renderer-enhancer.js`. Specifically, line 48.

```javascript
const initialState = objectMerge(providedInitialState || {}, preload);
```

Shouldn't we be merging in the `providedInitialState` into the preloaded state? If I am mistaken, please clarify for me. 

I will be submitting a PR in hopes that this issue can be resolved quickly.

**Comment by samiskin** [comment]
Published under 0.6.2
