### ISSUE TITLE
The UI actions of DevTools monitor cannot be apply main process store

### ISSUE THREAD

**Issue by jhen0409** [samiskin/redux-electron-store#6]
#### Renderer
```js
let finalCreateStore = compose(
  applyMiddleware(...middleware),
  electronEnhancer({filter}),
  DevTools.instrument()
)(createStore);
```

It seems obvious, the UI actions of LogMonitor cannot be apply to main process store, any plans to solve this problem?

**Comment by samiskin** [comment]
Something along the lines of this is what I did:

```javascript
let storeEnhancers = compose(
 ...
  applyMiddleware(thunk, logger)
);

if (process.type === 'renderer' && !process.guestInstanceId) {
  let DevTools = require('DevTools');
  storeEnhancers = compose(
    storeEnhancers,
    require('DevTools').instrument()
  );
}

let store = storeEnhancers(createStore)(reducer);
```

`process.type === 'renderer'` ensures that I'm not in the browser process, and `!process.guestInstanceId`  ensures I'm not in a webView.

If the renderer/browser specific parts get too much you can code two separate stores and export the right one based on which process you're in.
