### ISSUE TITLE
Cannot read property 'postDispatchCallback' of undefined

### ISSUE THREAD

**Issue by davej** [samiskin/redux-electron-store#7]
Did the following in my main process using `redux-electron-store@0.3.1` and `electron@0.36.7`.

```js
const electronEnhancer = require('redux-electron-store').electronEnhancer;
electronEnhancer();
```

And received the following error.

<img width="504" alt="screen shot 2016-02-04 at 11 57 57" src="https://cloud.githubusercontent.com/assets/26971/12814417/cc7b5f60-cb36-11e5-8c3e-7677303b55ef.png">

**Comment by davej** [comment]
Fixed this by passing in an empty object literal:

```js
electronEnhancer({});
```

It should probably be reflected in the docs or fixed in the code though.

**Comment by samiskin** [comment]
It should now work as `electronEnhancer()` in v0.3.2, thanks for the heads up.
