### ISSUE TITLE
Compatibility with redux-persist

### ISSUE THREAD

**Issue by davej** [samiskin/redux-electron-store#8]
I'm currently trying to get this working with [redux-persist](https://github.com/rt2zz/redux-persist/) but it overwrites the store data after redux-persist hydrates it. Any suggestions or tips for this use-case?

**Comment by samiskin** [comment]
`redux-persist` works through `localStorage` by default, which Electron's main process doesn't actually have.  Have you tried replacing the storage backend for redux-persist with one that can use file storage and using it in the main process?  If you have an action to rehydrate and use it in the main process, it should end up being forwarded to the renderer processes.

If that doesn't work another thing I was considering was just exporting a save and load function as well, which can take in a filter and persist the data that passes it from/into a file.

**Comment by davej** [comment]
Thanks, I'm actually using a custom store which basically reads/writes state to disk using node's `fs` module. I am only using `redux-persist` on the renderer, not on the main process. The variable that is being hydrated by `redux-persist` isn't included in the `redux-electron-store` filter so I assumed the electron-store wouldn't touch it.

Perhaps a save/load to disk function like you suggested, would eliminate my need for using `redux-persist` though?

**Comment by samiskin** [comment]
Hi sorry for the delay.

I had never actually considered having different reducers between processes.  In `0.3.3` I fixed the issue where it wouldn't work with having extra reducers in the renderer process.  I got the renderer process working with `redux-persist` by setting the whitelist to just the extra key I put in.

Extra reducers in the main process compared to the renderer process would have to be dealt with the filter.

Since persisting the main process data seems like a more common use case, did you encounter any troubles with persisting the main process' store with your custom store due to `redux-electron-store`?

**Comment by davej** [comment]
Yeah, I'm using `0.3.3`. I've changed my approach I am now rehydrating my app using a standard action + reducer, rather than using `redux-persist`. My code looks like this:

**main**
```js
function appReducer(state, action) {
  if (!state) state = { visible: false };
  switch (action.type) {
    case 'SHOW_APP':
      return Object.assign({}, state, { visible: true });
    case 'HIDE_APP':
      return Object.assign({}, state, { visible: false });
    default:
      return state;
  }
}

const reducer = combineReducers({ app: appReducer });
const enhancer = compose(reduxStore({ filter: { app: true } }));
const store = createStore(reducer, [], enhancer);

// ...

store.dispatch({
  type: 'SHOW_APP'
});

```

My enhancer in the **renderer** looks like this (in dev mode), my app reducer is the same:
```js
const enhancers = compose(
  electronEnhancer({
    filter: {
      app: true
    },
  }),
  applyMiddleware(thunk),
  DevTools.instrument(),
  persistState(
    window.location.href.match(
      /[?&]debug_session=([^&]+)\b/
    )
  ),
);
```

And this is the error that I'm getting when I launch the app:

<img width="532" alt="screen shot 2016-02-07 at 21 06 39" src="https://cloud.githubusercontent.com/assets/26971/12875309/12bd564a-cddf-11e5-9457-1bb962cc1ee0.png">

**Comment by samiskin** [comment]
I'm sadly swamped this week so I'l look into it over the weekend if I can, sorry for not being able to respond sooner.

**Comment by davej** [comment]
Ah, no problem at all. Thanks for your help.

**Comment by davej** [comment]
Shared all my reducers with the main process and it's working well now. A couple of small problems but I'll make new issues for them. I'll leave it up to you if you want to leave this issue open or close it.
